spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: test
    password: password

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 1234

  jpa:
    hibernate:
      ddl-auto: update # create-drop, create, update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 10MB # 파일 하나의 최대 크기
      max-request-size: 10MB # 한 요청의 최대 크기

jwt:
  # ?? ?? 32?? ????? ?
  secret: customConfigakdjfidfkemldmakldfjkejikdfmakmclkxmclmhsakfh

minio:
  url: http://localhost:9000 # minio API 포트 주소
  bucket:
    photo:
      name: photo # 사진 버킷 이름
    thumbnail:
      name: thumbnail  # 썸네일 버킷 이름
  access:
    name: mYYRwWTeR4IR9h4Db9lC   # access key
    secret: 6VeJ8wMOpITTLMdrWqXaoAY0TSUW5ud55AbaW71t # secretKey key